from setuptools import setup, find_packages

setup(
    name="adare",
    version="0.1.0",
    description="Automated Desktop Analysis framework for Reproducible Experiments",
    author="miqsoft",
    author_email="mksaxhandball@gmail.com",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "adarelib",
        "requests>=2.31.0",
        "sqlalchemy>=2.0.27",
        "jinja2>=3.1.3",
        "cattrs>=23.2.3",
        "sqlalchemy-serializer>=1.4.1",
        "pyyaml>=6.0.1",
        "nicegui>=1.4.15",
        "retry>=0.9.2",
        "prettytable>=3.9.0",
        "tqdm>=4.66.2",
        "prompt-toolkit>=3.0.43",
        "six>=1.16.0",
        "sphinx>=7.2.6",
        "sphinx-rtd-theme>=2.0.0",
        "watchdog>=4.0.0",
        "keyboard>=0.13.5",
        "python-ulid>=2.7.0",
        "textual-dev>=1.7.0",
        "textual>=2.1.1",
        "trogon>=0.6.0",
        "opencv-python>=4.8.0",
        "numpy>=1.24.0",
        "redis>=6.2.0",
        "pandas>=2.3.1",
        "fastmcp>=2.9.2",
        "websockets>=15.0",
    ],
    entry_points={
        "console_scripts": [
            "adare=adare.run:main",
            "adareexp=adare.example:main",
        ],
    },
)
