# name: {{ environment }}  # Optional: filename is used as environment name
vm: {% if vm_name %}"{{ vm_name }}"{% else %}"path/to/your/vm"{% endif %}
os:
  os: "Windows 10"
  platform: "windows"
  distribution: "Home"
  version: "21H1"
  language: "English"
# postsetupinstallations:
#   - name: "jinja2"
#     command: "pip3 install jinja2"
#     description: "tool to use templating in python"
#   - name: "datefinder"
#     command: "pip3 install datefinder"
