name: {{ environment }}
vagrantbox: "win10home21H1_english"
os:
  os: "Windows 10"
  platform: "windows"
  distribution: "Home"
  version: "21H1"
  language: "English"
postsetupinstallations:
  - name: "jinja2"
    command: "pip3 install jinja2"
    description: "tool to use templating in python"
  - name: "datefinder"
    command: "pip3 install datefinder"
  - name: "guibot"
    command: "pip3 install guibot"
  - name: "pyautogui"
    command: "pip3 install pyautogui"
    description: "tool to change resolution"
  - name: "opencv"
    command: "pip3 install opencv-python"
  - name: "tesseract"
    command: "choco install --no-progress -y tesseract"
  - name: "tesseract python"
    command: "pip3 install pytesseract"
