Vagrant.configure("2") do |config|

    config.vm.box = "{{ config_vm_box }}"
    {% if communicator %}config.vm.communicator = "{{ communicator }}"{% endif %}
    {% if ssh_shell %}config.ssh.shell = "{{ ssh_shell }}"{% endif %}
    {% for f in port_forwardings %}
    {% if f.id %}
    config.vm.network "forwarded_port", id: "{{ f.id }}", host: {{ f.host }}, guest: 22
    {% else %}
    config.vm.network "forwarded_port", guest: {{ f.guest }}, host: {{ f.host }}
    {% endif %}
    {% endfor %}

    config.vm.provider "virtualbox" do |vb|
        {% if virtualbox_memory %}vb.memory = {{ virtualbox_memory }}{% endif %}
        {% if virtualbox_cpus %}vb.cpus = {{ virtualbox_cpus }}{% endif %}
        {% if virtualbox_name %}vb.name = "{{ virtualbox_name }}"{% endif %}
        {% if virtualbox_gui %}vb.gui = true{% endif %}
        {% if virtualbox_modifyvm_usb_on %}vb.customize ["modifyvm", :id, "--usb", "on"]{% endif %}
        {% if virtualbox_modifyvm_usbehci_on %}vb.customize ["modifyvm", :id, "--usbehci", "on"]{% endif %}
        {% for usb in usbdevices -%}# usbname: {{ usb.name }}
        vb.customize {{ usb.vboxmanagecommand }}{%- endfor %}
    end
    {% for network in virtualbox_networks -%}
    config.vm.network "{{ network.vgname }}"{% for option in network.details -%},{{ option.key }}: "{{ option.value }}"{%- endfor %}
    {%- endfor %}

    {% if vagrant_disable_vbguestautoupdate %}
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end
    {% endif %}
    {% for prov in provisioners -%}
    config.vm.provision "{{ prov.type }}"{% for option in prov.provisioner_option -%}, {{ option.key }}: "{{ option.value }}"{%- endfor %}
    {% endfor %}

end
